export const countryList = [
  {
    id: 1,
    country: "India",
    capital: "New Delhi",
    continent: "Asia",
  },
  {
    id: 2,
    country: "China",
    capital: "Beijing",
    continent: "Asia",
  },
  {
    id: 3,
    country: "Singapore",
    capital: "Singapore",
    continent: "Asia",
  },
  {
    id: 4,
    country: "Malaysia",
    capital: "Kuala Lumpur",
    continent: "Asia",
  },
  {
    id: 5,
    country: "Japan",
    capital: "Tokyo",
    continent: "Asia",
  },
  {
    id: 6,
    country: "Pakistan",
    capital: "Islamabad",
    continent: "Asia",
  },
  {
    id: 7,
    country: "Bangladesh",
    capital: "Dhaka",
    continent: "Asia",
  },
  {
    id: 8,
    country: "Afghanistan",
    capital: "Kabul",
    continent: "Asia",
  },
  {
    id: 9,
    country: "Armenia",
    capital: "Yerevan",
    continent: "Asia",
  },
  {
    id: 10,
    country: "Azerbaijan",
    capital: "Baku",
    continent: "Asia",
  },
  {
    id: 11,
    country: "Bahrain",
    capital: "Manama",
    continent: "Asia",
  },
  {
    id: 12,
    country: "Bhutan",
    capital: "Thimphu",
    continent: "Asia",
  },
  {
    id: 13,
    country: "Cambodia",
    capital: "Phnom Penh",
    continent: "Asia",
  },
  {
    id: 14,
    country: "Indonesia",
    capital: "Jakarta",
    continent: "Asia",
  },
  {
    id: 15,
    country: "Iran",
    capital: "Tehran",
    continent: "Asia",
  },
  {
    id: 16,
    country: "Iraq",
    capital: "Baghdad",
    continent: "Asia",
  },
  {
    id: 17,
    country: "Vietnam",
    capital: "Hanoi",
    continent: "Asia",
  },

  {
    id: 18,
    country: "Yemen",
    capital: "Sana",
    continent: "Asia",
  },
  {
    id: 19,
    country: "Jordan",
    capital: "Amman",
    continent: "Asia",
  },
  {
    id: 20,
    country: "Kazakhstan",
    capital: "Nur-Sultan",
    continent: "Asia",
  },
  {
    id: 21,
    country: "North Korea",
    capital: "Pyongyang",
    continent: "Asia",
  },
  {
    id: 22,
    country: "South Korea",
    capital: "Seoul",
    continent: "Asia",
  },
  {
    id: 23,
    country: "Kuwait",
    capital: "Kuwait City",
    continent: "Asia",
  },
  {
    id: 24,
    country: "Kyrgyzstan",
    capital: "Bishkek",
    continent: "Asia",
  },
  {
    id: 25,
    country: "Laos",
    capital: "Vientiane",
    continent: "Asia",
  },
  {
    id: 26,
    country: "Lebanon",
    capital: "Beirut",
    continent: "Asia",
  },
  {
    id: 27,
    country: "Philippines",
    capital: "Manila",
    continent: "Asia",
  },
  {
    id: 28,
    country: "Maldives",
    capital: "Male",
    continent: "Asia",
  },
  {
    id: 29,
    country: "Mongolia",
    capital: "Ulaanbaatar",
    continent: "Asia",
  },
  {
    id: 30,
    country: "Myanmar",
    capital: "Naypyidau",
    continent: "Asia",
  },
  {
    id: 31,
    country: "Nepal",
    capital: "Kathmandu",
    continent: "Asia",
  },
  {
    id: 32,
    country: "Oman",
    capital: "Muscat",
    continent: "Asia",
  },
  {
    id: 33,
    country: "Palestine",
    capital: "East Jerusalem",
    continent: "Asia",
  },
  {
    id: 34,
    country: "Qatar",
    capital: "Doha",
    continent: "Asia",
  },
  {
    id: 35,
    country: "Saudi Arabia",
    capital: "Riyadh",
    continent: "Asia",
  },
  {
    id: 36,
    country: "Sri Lanka",
    capital: "Sri Jayawardenapura Kotte",
    continent: "Asia",
  },
  {
    id: 37,
    country: "Syria",
    capital: "Damascus",
    continent: "Asia",
  },
  {
    id: 38,
    country: "Taiwan",
    capital: "Taipei",
    continent: "Asia",
  },
  {
    id: 39,
    country: "Tajikistan",
    capital: "Dushanbe",
    continent: "Asia",
  },
  {
    id: 40,
    country: "Thailand",
    capital: "Bangkok",
    continent: "Asia",
  },
  {
    id: 41,
    country: "Turkey",
    capital: "Ankara",
    continent: "Asia",
  },
  {
    id: 42,
    country: "Turkmenistan",
    capital: "Ashgabat",
    continent: "Asia",
  },
  {
    id: 43,
    country: "United Arab Emirates",
    capital: "Abu Dhabi",
    continent: "Asia",
  },
  {
    id: 44,
    country: "Uzbekistan",
    capital: "Tashkent",
    continent: "Asia",
  },
  {
    id: 45,
    country: "Albania",
    capital: "Tirana",
    continent: "Europe",
  },
  {
    id: 46,
    country: "Andorra",
    capital: "Andorra la Vella",
    continent: "Europe",
  },
  {
    id: 47,
    country: "Austria",
    capital: "Vienna",
    continent: "Europe",
  },
  {
    id: 48,
    country: "Belarus",
    capital: "Minsk",
    continent: "Europe",
  },
  {
    id: 49,
    country: "Belgium",
    capital: "Brussels",
    continent: "Europe",
  },
  {
    id: 50,
    country: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    continent: "Europe",
  },
  {
    id: 51,
    country: "Bulgaria",
    capital: "Sofia",
    continent: "Europe",
  },
  {
    id: 52,
    country: "Croatia",
    capital: "Zagreb",
    continent: "Europe",
  },
  {
    id: 53,
    country: "Cyprus",
    capital: "Nicosia",
    continent: "Europe",
  },
  {
    id: 54,
    country: "Czech Republic",
    capital: "Prague",
    continent: "Europe",
  },
  {
    id: 55,
    country: "Denmark",
    capital: "Copenhagen",
    continent: "Europe",
  },
  {
    id: 56,
    country: "Estonia",
    capital: "Tallinn",
    continent: "Europe",
  },
  {
    id: 57,
    country: "Finland",
    capital: "Helsinki",
    continent: "Europe",
  },
  {
    id: 58,
    country: "France",
    capital: "Paris",
    continent: "Europe",
  },
  {
    id: 59,
    country: "Georgia",
    capital: "Tbilisi",
    continent: "Europe",
  },
  {
    id: 60,
    country: "Germany",
    capital: "Berlin",
    continent: "Europe",
  },
  {
    id: 61,
    country: "Hungary",
    capital: "Budapest",
    continent: "Europe",
  },
  {
    id: 62,
    country: "Iceland",
    capital: "Reykjavik",
    continent: "Europe",
  },
  {
    id: 63,
    country: "Ireland",
    capital: "Dublin",
    continent: "Europe",
  },
  {
    id: 64,
    country: "Italy",
    capital: "Rome",
    continent: "Europe",
  },
  {
    id: 65,
    country: "Kosovo",
    capital: "Pristina",
    continent: "Europe",
  },
  {
    id: 66,
    country: "Latvia",
    capital: "Riga",
    continent: "Europe",
  },
  {
    id: 67,
    country: "Liechtenstein",
    capital: "Vaduz",
    continent: "Europe",
  },
  {
    id: 68,
    country: "Lithuania",
    capital: "Vilnius",
    continent: "Europe",
  },
  {
    id: 69,
    country: "Luxembourg",
    capital: "Luxembourg City",
    continent: "Europe",
  },
  {
    id: 70,
    country: "Malta",
    capital: "Valletta",
    continent: "Europe",
  },
  {
    id: 71,
    country: "Monaco",
    capital: "Monaco",
    continent: "Europe",
  },
  {
    id: 72,
    country: "Montenegro",
    capital: "Podgorica",
    continent: "Europe",
  },
  {
    id: 73,
    country: "Netherlands",
    capital: "Amsterdam",
    continent: "Europe",
  },
  {
    id: 74,
    country: "North Macedonia",
    capital: "Skopje",
    continent: "Europe",
  },
  {
    id: 75,
    country: "Norway",
    capital: "Oslo",
    continent: "Europe",
  },
  {
    id: 76,
    country: "Poland",
    capital: "Warsaw",
    continent: "Europe",
  },
  {
    id: 77,
    country: "Portugal",
    capital: "Lisbon",
    continent: "Europe",
  },
  {
    id: 78,
    country: "Romania",
    capital: "Bucharest",
    continent: "Europe",
  },
  {
    id: 79,
    country: "Russia",
    capital: "Moscow",
    continent: "Europe",
  },
  {
    id: 80,
    country: "San Marino",
    capital: "San Marino",
    continent: "Europe",
  },
  {
    id: 81,
    country: "Serbia",
    capital: "Belgrade",
    continent: "Europe",
  },
  {
    id: 82,
    country: "Slovakia",
    capital: "Bratislava",
    continent: "Europe",
  },
  {
    id: 83,
    country: "Slovenia",
    capital: "Ljubljana",
    continent: "Europe",
  },
  {
    id: 84,
    country: "Spain",
    capital: "Madrid",
    continent: "Europe",
  },
  {
    id: 85,
    country: "Sweden",
    capital: "Stockholm",
    continent: "Europe",
  },
  {
    id: 86,
    country: "Switzerland",
    capital: "Bern",
    continent: "Europe",
  },
  {
    id: 87,
    country: "Turkey",
    capital: "Ankara",
    continent: "Europe",
  },
  {
    id: 88,
    country: "Ukraine",
    capital: "Kiev",
    continent: "Europe",
  },
  {
    id: 89,
    country: "United Kingdom",
    capital: "London",
    continent: "Europe",
  },
  {
    id: 90,
    country: "Vatican City",
    capital: "Vatican City",
    continent: "Europe",
  },
  {
    id: 91,
    country: "Australia",
    capital: "Canberra",
    continent: "Australia",
  },
  {
    id: 92,
    country: "New South Wales",
    capital: "Sydney",
    continent: "Australia",
  },
  {
    id: 93,
    country: "Northern Territory",
    capital: "Darwin",
    continent: "Australia",
  },
  {
    id: 94,
    country: "Queensland",
    capital: "Brisbane",
    continent: "Australia",
  },
  {
    id: 95,
    country: "South Australia",
    capital: "Adelaide",
    continent: "Australia",
  },
  {
    id: 96,
    country: "Tasmania",
    capital: "Hobart",
    continent: "Australia",
  },
  {
    id: 97,
    country: "Victoria",
    capital: "Melbourne",
    continent: "Australia",
  },
  {
    id: 98,
    country: "Western Australia",
    capital: "Perth",
    continent: "Australia",
  },
  {
    id: 99,
    country: "United States",
    capital: "Washington D.C.",
    continent: "North America",
  },
  {
    id: 100,
    country: "Canada",
    capital: "Ottawa",
    continent: "North America",
  },
  {
    id: 101,
    country: "Costa Rica",
    capital: "San Jose",
    continent: "North America",
  },
  {
    id: 102,
    country: "Dominican Republic",
    capital: "Santo Domingo",
    continent: "North America",
  },
  {
    id: 103,
    country: "Dominica",
    capital: "Roseau",
    continent: "North America",
  },
  {
    id: 104,
    country: "Jamaica",
    capital: "Kingston",
    continent: "North America",
  },
  {
    id: 105,
    country: "Trinidad and Tobago",
    capital: "Port of Spain",
    continent: "North America",
  },
  {
    id: 106,
    country: "El Salvador",
    capital: "San Salvador",
    continent: "North America",
  },
  {
    id: 107,
    country: "Mexico",
    capital: "Mexico City",
    continent: "North America",
  },
  {
    id: 108,
    country: "Grenada",
    capital: "St. George's",
    continent: "North America",
  },
  {
    id: 109,
    country: "Guatemala",
    capital: "Guatemala City",
    continent: "North America",
  },
  {
    id: 110,
    country: "Antigua and Barbuda",
    capital: "St. John's",
    continent: "North America",
  },
  {
    id: 111,
    country: "Haiti",
    capital: "Port-au-Prince",
    continent: "North America",
  },
  {
    id: 112,
    country: "Honduras",
    capital: "Tegucigalpa",
    continent: "North America",
  },
  {
    id: 113,
    country: "Saint Lucia",
    capital: "Castries",
    continent: "North America",
  },
  {
    id: 114,
    country: "Greenland",
    capital: "Nuuk",
    continent: "North America",
  },
  {
    id: 115,
    country: "Puerto Rico",
    capital: "San Juan",
    continent: "North America",
  },
  {
    id: 116,
    country: "Belize",
    capital: "Belmopan",
    continent: "North America",
  },
  {
    id: 117,
    country: "Bahamas",
    capital: "Nassau",
    continent: "North America",
  },
  {
    id: 118,
    country: "Cuba",
    capital: "Havana",
    continent: "North America",
  },
  {
    id: 119,
    country: "Nicaragua",
    capital: "Managua",
    continent: "North America",
  },
  {
    id: 120,
    country: "Barbados",
    capital: "Bridgetown",
    continent: "North America",
  },
  {
    id: 121,
    country: "Panama",
    capital: "Panama City",
    continent: "North America",
  },
  {
    id: 122,
    country: "Saint Kitts and Nevis",
    capital: "Basseterre",
    continent: "North America",
  },
  {
    id: 123,
    country: "Saint Vincent and the Grenadines",
    capital: "Kingstown",
    continent: "North America",
  },
  {
    id: 124,
    country: "Argentina",
    capital: "Buenos Aires",
    continent: "South America",
  },
  {
    id: 125,
    country: "Bolivia",
    capital: "Sucre",
    continent: "South America",
  },
  {
    id: 126,
    country: "Brazil",
    capital: "Brasilia",
    continent: "South America",
  },
  {
    id: 127,
    country: "Chile",
    capital: "Santiago",
    continent: "South America",
  },
  {
    id: 128,
    country: "Colombia",
    capital: "Bogota",
    continent: "South America",
  },
  {
    id: 129,
    country: "Ecuador",
    capital: "Quito",
    continent: "South America",
  },
  {
    id: 130,
    country: "Guyana",
    capital: "Georgetown",
    continent: "South America",
  },
  {
    id: 131,
    country: "Paraguay",
    capital: "Asuncion",
    continent: "South America",
  },
  {
    id: 132,
    country: "Peru",
    capital: "Lima",
    continent: "South America",
  },
  {
    id: 133,
    country: "Suriname",
    capital: "Paramaribo",
    continent: "South America",
  },
  {
    id: 134,
    country: "Uruguay",
    capital: "Montevideo",
    continent: "South America",
  },
  {
    id: 135,
    country: "Venezuela",
    capital: "Caracas",
    continent: "South America",
  },
  {
    id: 136,
    country: "Algeria",
    capital: "Algiers",
    continent: "Africa",
  },
  {
    id: 137,
    country: "Angola",
    capital: "Luanda",
    continent: "Africa",
  },
  {
    id: 138,
    country: "Benin",
    capital: "Porto-Novo",
    continent: "Africa",
  },
  {
    id: 139,
    country: "Botswana",
    capital: "Gaborone",
    continent: "Africa",
  },
  {
    id: 140,
    country: "Burkina Faso",
    capital: "Ouagadougou",
    continent: "Africa",
  },
  {
    id: 141,
    country: "Burundi",
    capital: "Gitega",
    continent: "Africa",
  },
  {
    id: 142,
    country: "Cameroon",
    capital: "Yaounde",
    continent: "Africa",
  },
  {
    id: 143,
    country: "Cape Verde",
    capital: "Praia",
    continent: "Africa",
  },
  {
    id: 144,
    country: "Central African Republic",
    capital: "Bangui",
    continent: "Africa",
  },
  {
    id: 145,
    country: "Chad",
    capital: "N'Djamena",
    continent: "Africa",
  },
  {
    id: 146,
    country: "Comoros",
    capital: "Moroni",
    continent: "Africa",
  },
  {
    id: 147,
    country: "Congo Democratic Republic",
    capital: "Kinshasa",
    continent: "Africa",
  },
  {
    id: 148,
    country: "Congo Republic",
    capital: "Brazzaville",
    continent: "Africa",
  },
  {
    id: 149,
    country: "Cote d Ivoire",
    capital: "Yamoussoukro",
    continent: "Africa",
  },
  {
    id: 150,
    country: "Djibouti",
    capital: "Djibouti",
    continent: "Africa",
  },
  {
    id: 151,
    country: "Egypt",
    capital: "Cairo",
    continent: "Africa",
  },
  {
    id: 152,
    country: "Equatorial Guinea",
    capital: "Malabo",
    continent: "Africa",
  },
  {
    id: 153,
    country: "Eritrea",
    capital: "Asmara",
    continent: "Africa",
  },
  {
    id: 154,
    country: "Ethiopia",
    capital: "Addis Ababa",
    continent: "Africa",
  },
  {
    id: 155,
    country: "Gabon",
    capital: "Libreville",
    continent: "Africa",
  },
  {
    id: 156,
    country: "Gambia",
    capital: "Banjul",
    continent: "Africa",
  },
  {
    id: 157,
    country: "Ghana",
    capital: "Accra",
    continent: "Africa",
  },
  {
    id: 158,
    country: "Guinea",
    capital: "Conakry",
    continent: "Africa",
  },
  {
    id: 159,
    country: "Guinea Bissau",
    capital: "Bissau",
    continent: "Africa",
  },
  {
    id: 160,
    country: "Kenya",
    capital: "Nairobi",
    continent: "Africa",
  },
  {
    id: 161,
    country: "Lesotho",
    capital: "Maseru",
    continent: "Africa",
  },
  {
    id: 162,
    country: "Liberia",
    capital: "Monrovia",
    continent: "Africa",
  },
  {
    id: 163,
    country: "Libya",
    capital: "Tripoli",
    continent: "Africa",
  },
  {
    id: 164,
    country: "Madagascar",
    capital: "Antananarivo",
    continent: "Africa",
  },
  {
    id: 165,
    country: "Malawi",
    capital: "Lilongwe",
    continent: "Africa",
  },
  {
    id: 166,
    country: "Mali",
    capital: "Bamako",
    continent: "Africa",
  },
  {
    id: 167,
    country: "Mauritania",
    capital: "Nouakchott",
    continent: "Africa",
  },
  {
    id: 168,
    country: "Mauritius",
    capital: "Port Louis",
    continent: "Africa",
  },
  {
    id: 169,
    country: "Morocco",
    capital: "Rabat",
    continent: "Africa",
  },
  {
    id: 170,
    country: "Mozambique",
    capital: "Maputo",
    continent: "Africa",
  },
  {
    id: 171,
    country: "Namibia",
    capital: "Windhoek",
    continent: "Africa",
  },
  {
    id: 172,
    country: "Niger",
    capital: "Niamey",
    continent: "Africa",
  },
  {
    id: 173,
    country: "Nigeria",
    capital: "Abuja",
    continent: "Africa",
  },
  {
    id: 174,
    country: "Rwanda",
    capital: "Kigali",
    continent: "Africa",
  },
  {
    id: 175,
    country: "Republic Arab Saharawi Democratic",
    capital: "Aavin",
    continent: "Africa",
  },
  {
    id: 176,
    country: "Sao Tome and Principe",
    capital: "Sao Tome",
    continent: "Africa",
  },
  {
    id: 177,
    country: "Senegal",
    capital: "Dakar",
    continent: "Africa",
  },
  {
    id: 178,
    country: "Seychelles",
    capital: "Victoria",
    continent: "Africa",
  },
  {
    id: 179,
    country: "Sierra Leone",
    capital: "Freetown",
    continent: "Africa",
  },
  {
    id: 180,
    country: "South Africa",
    capital: "Pretoria",
    continent: "Africa",
  },
  {
    id: 181,
    country: "South Sudan",
    capital: "Juba",
    continent: "Africa",
  },
  {
    id: 182,
    country: "Sudan",
    capital: "Khartoum",
    continent: "Africa",
  },
  {
    id: 183,
    country: "Eswatini",
    capital: "Lobamba and Mbabane",
    continent: "Africa",
  },
  {
    id: 184,
    country: "Tanzania",
    capital: "Dodoma",
    continent: "Africa",
  },
  {
    id: 185,
    country: "Togo",
    capital: "Lomé",
    continent: "Africa",
  },
  {
    id: 186,
    country: "Tunisia",
    capital: "Tunis",
    continent: "Africa",
  },
  {
    id: 187,
    country: "Uganda",
    capital: "Kampala",
    continent: "Africa",
  },
  {
    id: 188,
    country: "Zambia",
    capital: "Lusaka",
    continent: "Africa",
  },
  {
    id: 189,
    country: "Zimbabwe",
    capital: "Harare",
    continent: "Africa",
  },
];

export const asiaCapitalsList = countryList
  .filter((country) => country.continent === "Asia")
  .map((filteredCountry) => filteredCountry.capital);

export const europeCapitalsList = countryList
  .filter((country) => country.continent === "Europe")
  .map((filteredCountry) => filteredCountry.capital);

export const australiaCapitalsList = countryList
  .filter((country) => country.continent === "Australia")
  .map((filteredCountry) => filteredCountry.capital);

export const northAmericaCapitalsList = countryList
  .filter((country) => country.continent === "North America")
  .map((filteredCountry) => filteredCountry.capital);

export const southAmericaCapitalsList = countryList
  .filter((country) => country.continent === "South America")
  .map((filteredCountry) => filteredCountry.capital);

export const africaCapitalsList = countryList
  .filter((country) => country.continent === "Africa")
  .map((filteredCountry) => filteredCountry.capital);
