export const countryList = [
  {
    id: 1,
    country: "India",
    capital: "New Delhi",
    continent: "Asia",
  },
  {
    id: 2,
    country: "China",
    capital: "Beijing",
    continent: "Asia",
  },
  {
    id: 3,
    country: "Singapore",
    capital: "Singapore",
    continent: "Asia",
  },
  {
    id: 4,
    country: "Malaysia",
    capital: "Kaula Lampur",
    continent: "Asia",
  },
  {
    id: 5,
    country: "Japan",
    capital: "Tokyo",
    continent: "Asia",
  },
  {
    id: 6,
    country: "Pakistan",
    capital: "Islamabad",
    continent: "Asia",
  },
  {
    id: 7,
    country: "Bangladesh",
    capital: "Dhaka",
    continent: "Asia",
  },
  {
    id: 8,
    country: "Afghanistan",
    capital: "Kabul",
    continent: "Asia",
  },
  {
    id: 9,
    country: "Armenia",
    capital: "Yerevan",
    continent: "Asia",
  },
  {
    id: 10,
    country: "Azerbaijan",
    capital: "Baku",
    continent: "Asia",
  },
  {
    id: 11,
    country: "Bharain",
    capital: "Manama",
    continent: "Asia",
  },
  {
    id: 12,
    country: "Bhutan",
    capital: "Thimpu",
    continent: "Asia",
  },
  {
    id: 13,
    country: "Cambodia",
    capital: "Phnom penh",
    continent: "Asia",
  },
  {
    id: 14,
    country: "Indonesia",
    capital: "Jakarta",
    continent: "Asia",
  },
  {
    id: 15,
    country: "Iran",
    capital: "Tehran",
    continent: "Asia",
  },
  {
    id: 16,
    country: "Iraq",
    capital: "Baghdad",
    continent: "Asia",
  },
  {
    id: 17,
    country: "Veitnam",
    capital: "Hanoi",
    continent: "Asia",
  },

  {
    id: 18,
    country: "Yemen",
    capital: "Sana",
    continent: "Asia",
  },
  {
    id: 19,
    country: "Jordan",
    capital: "Aman",
    continent: "Asia",
  },
  {
    id: 20,
    country: "Kazakhstan",
    capital: "Astana",
    continent: "Asia",
  },
  {
    id: 21,
    country: "North Korea",
    capital: "Pyongyaug",
    continent: "Asia",
  },
  {
    id: 22,
    country: "South Korea",
    capital: "Seol",
    continent: "Asia",
  },
  {
    id: 23,
    country: "Kuwait",
    capital: "Kuwait City",
    continent: "Asia",
  },
  {
    id: 24,
    country: "Kyrgyztan",
    capital: "Bishkek",
    continent: "Asia",
  },
  {
    id: 25,
    country: "Laos",
    capital: "Vientiane",
    continent: "Asia",
  },
  {
    id: 26,
    country: "Lebanon",
    capital: "Beirutt",
    continent: "Asia",
  },
  {
    id: 27,
    country: "Philippines",
    capital: "Manila",
    continent: "Asia",
  },
  {
    id: 28,
    country: "Maldives",
    capital: "Male",
    continent: "Asia",
  },
  {
    id: 29,
    country: "Mangolia",
    capital: "Ulaanbaator",
    continent: "Asia",
  },
  {
    id: 30,
    country: "Myanmar",
    capital: "Naypyidau",
    continent: "Asia",
  },
  {
    id: 31,
    country: "Nepal",
    capital: "Khatmandu",
    continent: "Asia",
  },
  {
    id: 32,
    country: "Omen",
    capital: "Muskat",
    continent: "Asia",
  },
  {
    id: 33,
    country: "Palestine",
    capital: "East Jerusalem",
    continent: "Asia",
  },
  {
    id: 34,
    country: "Quatar",
    capital: "Doha",
    continent: "Asia",
  },
  {
    id: 35,
    country: "Saudi Arabia",
    capital: "Riyadh",
    continent: "Asia",
  },
  {
    id: 36,
    country: "Srilanka",
    capital: "Sri Jayawardenapura Kotte",
    continent: "Asia",
  },
  {
    id: 37,
    country: "Syria",
    capital: "Damascus",
    continent: "Asia",
  },
  {
    id: 38,
    country: "Taiwan",
    capital: "Taipei",
    continent: "Asia",
  },
  {
    id: 39,
    country: "Tajikistan",
    capital: "Dushanbe",
    continent: "Asia",
  },
  {
    id: 40,
    country: "Thailand",
    capital: "Bangkok",
    continent: "Asia",
  },
  {
    id: 41,
    country: "Turkey",
    capital: "Ankara",
    continent: "Asia",
  },
  {
    id: 42,
    country: "Turkmenistan",
    capital: "Ashgabat",
    continent: "Asia",
  },
  {
    id: 43,
    country: "United Arab Emirates (UAE)",
    capital: "Abu Dhabi",
    continent: "Asia",
  },
  {
    id: 44,
    country: "Uzbekistan",
    capital: "Tashkent",
    continent: "Asia",
  },
  {
    id: 45,
    country: "Albania",
    capital: "Tirana",
    continent: "Europe",
  },
  {
    id: 46,
    country: "Andorra",
    capital: "Andorra la vella",
    continent: "Europe",
  },
  {
    id: 47,
    country: "Austria",
    capital: "Vienna",
    continent: "Europe",
  },
  {
    id: 48,
    country: "Belarus",
    capital: "Minsk",
    continent: "Europe",
  },
  {
    id: 49,
    country: "Belgium",
    capital: "Brussels",
    continent: "Europe",
  },
  {
    id: 50,
    country: "Bosnia and Herzegovina",
    capital: "Sarajevo",
    continent: "Europe",
  },
  {
    id: 51,
    country: "Bulgaria",
    capital: "Sofia",
    continent: "Europe",
  },
  {
    id: 52,
    country: "Croatia",
    capital: "Zagreb",
    continent: "Europe",
  },
  {
    id: 53,
    country: "Cyprus",
    capital: "Nicosia",
    continent: "Europe",
  },
  {
    id: 54,
    country: "Czechia (Czech Republic)",
    capital: "Prague",
    continent: "Europe",
  },
];

export const asiaCapitalsList = countryList
  .filter((country) => country.continent === "Asia")
  .map((filteredCountry) => filteredCountry.capital);

export const europeCapitalsList = countryList
  .filter((country) => country.continent === "Europe")
  .map((filteredCountry) => filteredCountry.capital);
